/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceisw;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author rabaj
 */
public class MetodologiasAgiles extends javax.swing.JFrame {

    /**
     * Creates new form Scrum
     */
    public MetodologiasAgiles() {
        initComponents();
        getContentPane().setBackground(new Color (0,61,121));
        ImageIcon imagen1=new ImageIcon(getClass().getResource("/imagenes/teoriais-head.png"));
        Icon fondo1=new ImageIcon(imagen1.getImage().getScaledInstance(dorado2.getWidth(), dorado2.getHeight(), Image.SCALE_DEFAULT));
        dorado2.setIcon(fondo1);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dorado2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teoría básica de ingeniería de software.");
        setResizable(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextArea1.setBackground(new java.awt.Color(213, 159, 15));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("¿que es Ingeniería de software?\nR= es un enfoque disciplinado, sistemático y cuantificable al desarrollo, mantenimiento y operación del software\n\n¿que es una fase de desarrollo de software?\nR=son métodos que indican como se debe de desarrollar el software e manera técnica y concisa.\n\n¿cuales son las diferentes fases de desarrollo de software?\nR= -análisis y definición de requerimientos (delimita el alcance que tendrá el sistema)\n   -Diseño del sistema (definirá la estructura que llevara el producto a ser desarrollado)\n   -Desarrollo del sistema (comienza la codificación del sistema)\n   -Pruebas unitarias (realiza pruebas por segmentos de código haciendo mas fácil detectar errores de manera temprana)\n   -Pruebas del sistema (verifica que el programa desarrollado cumpla las funciones iniciales)\n   -implementación del sistema (consiste en poner a funcionar el programa desarrollado luego de cumplir los puntos anteriores)\n   -Mantenimiento (realizar las actualizaciones pertinentes para que siga en uso el programa)\n   -post-mortem (fin del ciclo de vida del producto)\n\n¿que es calidad de software?\nR=es aquel que cumple con los requerimientos dados por el usuario final del producto desarrollado\n\n¿que es una herramienta dentro de la ingeniería de software?\nR= es un instrumento o sistema automatizado que realiza de manera mas exacta eficiente y productiva una tarea sencilla\n\n¿Que es un proceso en la ingeniería de software?\nR=es un conjunto de actividades que permiten transformar los requisitos de un usario en un sistema funcional de software\n\n¿que es una herramienta de modelado de software?\nR=son herramientas que usan los programadores que facilita su trabajo por medio de la utilización de diagramas UML\n");
        jScrollPane1.setViewportView(jTextArea1);

        dorado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 61, 121)));

        jButton1.setBackground(new java.awt.Color(213, 159, 15));
        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 61, 121));
        jButton1.setText("Boooooton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dorado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jButton1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dorado2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodologiasAgiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodologiasAgiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodologiasAgiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodologiasAgiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodologiasAgiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dorado2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
